[package]
name = "agente"
description = "A AI assistant that lives in your terminal."
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = [ "crates/application","crates/domain", "crates/infrastructure"]

[workspace.dependencies]
async-trait = "0.1.89"
tokio = { version = "1.48.0", features = ["full"] }

[dependencies]
agente-application = { path = "crates/application" }
agente-domain = { path = "crates/domain" }
agente-infrastructure = { path = "crates/infrastructure" }
async-trait = { workspace = true }
tokio = { workspace = true }
