use serde::Deserialize;

/// This model represents a task that can be generated by a `Agent` response.
#[derive(Debug, Deserialize)]
pub struct Task {
    /// Its tool identifier that can be used to find the tool in structured
    /// collection.
    tool: String,
    /// Describes what will be done by the tool
    summary: String,
    /// Is the tool arguments needed to properly execute the tool handler
    arguments: Vec<String>,
}

impl Task {
    pub fn new(tool: String, summary: String, arguments: Vec<String>) -> Self {
        Self {
            tool,
            summary,
            arguments,
        }
    }

    pub fn tool(&self) -> String {
        self.tool.clone()
    }

    pub fn summary(&self) -> String {
        self.summary.clone()
    }

    pub fn arguments(&self) -> Vec<String> {
        self.arguments.clone()
    }
}
