[package]
name = "agente-application"
version = "0.1.0"
edition = "2024"

[dependencies]
agente-domain = { path = "../domain" }
agente-infrastructure = { path = "../infrastructure" }
async-recursion = "1.1.1"
sqlx = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
