[package]
name = "agente-domain"
description = "This packages holds the agente interfaces for the domain implementaition"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
chrono = { version = "0.4.44", features = ["serde"] }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = "2.0.17"
uuid = { workspace = true }
